### ISSUE TITLE
Paypal without dropin directive

### ISSUE THREAD

**Issue by that1guy** [jeffcarp/braintree-angular#10]
I'm building a workflow where the user first chooses if they want to use creditcard, paypal, or apple pay.

Then depending on what they choose I begin the transaction.  I'm not using the dropin directive and instead I'm using the Advanced integration method which is working perfectly for credit cards.

How do I get the payPal button to run a paypal transaction via braintree's checkout method.  I'm at a loss.

Thanks for clarity!

###### Payment controller
````
htsApp.controller('paymentController', ['$scope', '$braintree', '$http', '$stateParams', 'ENV', function($scope, $braintree, $http, $stateParams, ENV) {

    //Credit card angular form populates this obj
    $scope.creditCard = {
        cardholderName: null,
        number: null,
        expirationMonth: null,
        expirationYear:  null,
        cvv: null
    };


    var client;
    
    //When the user selects a payment method this function is kicked off.
    $scope.selectPaymentMethod = function (paymentType) {


        if(paymentType === 'creditCard'){

            $braintree.getClientToken().success(function(token) {
                client = new $braintree.api.Client({
                    clientToken: token
                });
            });
            $scope.selectedPaymentMethod = paymentType; //This hides all the payment choices and shows the credit card form.

        } else if (paymentType === 'payPal') {

            $scope.selectedPaymentMethod = paymentType; //This hides all the payment choices.. how do I get paypal button to show up?
        }

    };

    //When the user clicks the submit button after entering their credit card credentials this kicks off.
    $scope.runCreditCard = function() {

        // - Validate $scope.creditCard
        // - Make sure client is ready to use

        client.tokenizeCard({
            number: $scope.creditCard.number,
            cardholderName: $scope.creditCard.cardholderName,
            expirationMonth: $scope.creditCard.expirationMonth,
            expirationYear: $scope.creditCard.expirationYear,
            cvv: $scope.creditCard.cvv
        }, function (err, nonce) {

            // - Send nonce to your server (e.g. to make a transaction)
            $http.post(ENV.braintreeAPI + '/purchase', {payment_method_nonce: nonce}).success(function(response){
                console.log(response);
            });

        });
    };
}]);
````

**Comment by jeffcarp** [comment]
Hey @that1guy! Thanks for bringing this up.

This repo doesn't currently support the [standalone PayPal button](https://developers.braintreepayments.com/javascript/guides/paypal/client-side). Looks like it's worth adding, though.

> apple pay

I'm very curious to hear how this works, is this a mobile app or a website?

> `$http.post(ENV.braintreeAPI + '/purchase', {payment_method_nonce: nonce}`

Shouldn't this be `post`ing to your API, not Braintree's?

**Comment by that1guy** [comment]
Thanks for clarification.  Given this fact I think I'll just stick with dropin directive for now.

Re: Apply Pay -- this is a webapp, therefore Apple Pay isn't possible I just read.  Must be native iOS app.

That API I'm posting to is actually my endpoint.  It's just poorly named.

Looking forward to the repo evolving.  Cheers!

**Comment by that1guy** [comment]
Actually the dropin doesn't ask for cvv or address.  Wonder if transactions will still go though in production.. hrmm.

**Comment by jeffcarp** [comment]
@that1guy if you have CVV verification enabled, Drop-in will add a CVV field. I don't think addresses/AVS are supported, though.

**Comment by that1guy** [comment]
Got it. Guess the testing shall begin then.

**Comment by jeffcarp** [comment]
Yeah that's unfortunate about Apple Pay, it would be awesome to have on web. Maybe they're working on it?

I just started a messy branch for getting PayPal standalone working. I can't make any promises but it'd be great to be able to PR this soon and get it into the module. Thanks for the feedback!
https://github.com/jeffcarp/braintree-angular/blob/paypal2/examples/dropin/nonce-received.html#L11

**Comment by that1guy** [comment]
Awesome.. will take a look.  Thanks Jeff!
