### ISSUE TITLE
Doesn't use inline array annotation syntax

### ISSUE THREAD

**Issue by ExplodingCabbage** [jeffcarp/braintree-angular#13]
The library currently [doesn't use](https://github.com/jeffcarp/braintree-angular/blob/master/dist/braintree-angular.js#L57) Angular's [dependency annotation syntax](https://docs.angularjs.org/guide/di#dependency-annotation). Consequently, it is minification-unfriendly and depending upon it will throw an error with `ng-strict-di` enabled.

**Comment by jeffcarp** [comment]
Thanks for pointing that out, @ExplodingCabbage! :+1: :smile:

**Comment by jlforever** [comment]
@jeffcarp first of all, thanks for coding out this library, very easy to use.

I noticed that the <braintree-dropin> directive is using the angular DI correctly, with the fix mentioned in this issue ticket. However the <braintree-paypal> directive is still not, https://github.com/jeffcarp/braintree-angular/blob/master/lib/braintree-angular.js#L36, is that done on purpose? 

I have had issues with the <braintree-paypal> directive working out properly in local environment, but when pushed to heroku, will bomb out with unknow eProvider issue.

**Comment by jlforever** [comment]
By the way, if you want, I can issue a pull request against the latest 1.4.0 release.

**Comment by jeffcarp** [comment]
It is not intentional, just an oversight. A PR would be appreciated! Otherwise I can get to it soon.

**Comment by jlforever** [comment]
@jeffcarp I just opened a PR, and made a note about uncertainties surrounding directly changing the `dist/braintree-angular.js` is kosher or not, and some other observation/verification notes.

**Comment by jeffcarp** [comment]
> directly changing the dist/braintree-angular.js

That file will be overwritten before publishing, so as long as the source is good then everything's good 😎
