### ISSUE TITLE
No support for 'paypal' integration

### ISSUE THREAD

**Issue by ExplodingCabbage** [jeffcarp/braintree-angular#14]
This is essentially a duplicate of https://github.com/jeffcarp/braintree-angular/issues/10. This library [doesn't currently support](https://github.com/jeffcarp/braintree-angular/issues/10#issuecomment-100589944) the standalone PayPal button. This wasn't obvious to me when I was considering using the library for that exact purpose, so I thought I'd open an issue just to increase visibility of the fact that this feature is not yet implemented.

**Comment by jeffcarp** [comment]
Thanks for being on top of this @ExplodingCabbage! I referenced the WIP PR and will close this thread once that's merged.

**Comment by jeffcarp** [comment]
[1.3.0](https://github.com/jeffcarp/braintree-angular/releases/tag/1.3.0) is out with PayPal button support! :fireworks: :smiley_cat:
