### ISSUE TITLE
add support for angular-meteor?

### ISSUE THREAD

**Issue by vacarsu** [jeffcarp/braintree-angular#16]
Think support could be added for meteor? tried adding support myself, but when I tried to bring it into the meteor client braintree-web errored with Navigator is undefined.

**Comment by jeffcarp** [comment]
I don't have the time to add support for angular-meteor but PRs are certainly welcome.

**Comment by vacarsu** [comment]
Okay, I will see if I can figure it out.

**Comment by jeffcarp** [comment]
Closing, feel free to re-open for any developments on this.
