### ISSUE TITLE
Forcing default restrict on directives

### ISSUE THREAD

**Issue by gambry** [jeffcarp/braintree-angular#17]
On a couples of project I'm working on I couldn't get the module working due the default restrict being 'E'. 

I'm not sure if this is a bug or something changed somewhere (the angular version I'm using, some hidden misconfiguration in some libraries,etc.) but it would be really useful to force the Angular default restrict value 'EA' on the braintree-angular module directives.

So the README examples will always work, avoiding headaches.

**Comment by jeffcarp** [comment]
Sorry this is late. Interesting, I thought that if you didn't specify a `restrict`, it would allow all of them. Why not set it to `restrict: 'AEC'` to cover all cases?

**Comment by gambry** [comment]
Your are right, not specifying `restrict` should fallback to the default `'AE'` but it doesn't and I'm not sure why. 

Besides that's the reason why I was suggesting to use `restrict: 'AE'`, because that's the default and probably people are expecting it.
I would stuck with 'AE'.

**Comment by jeffcarp** [comment]
I'm not really supportive of merging something unless we know the root cause. An Angular issue or line number would be good evidence to have before moving forward with this.

I'd choose 'AEC'. Why limit use cases when you don't have to?

**Comment by gambry** [comment]
'AEC' is fine as the examples on the TODO are covered, which IMO is the most important thing.

I found [the reason](http://stackoverflow.com/questions/16447762/angularjs-why-do-custom-directives-default-to-being-attribute-only): I'm using Angular 1.2 and defaulting to 'EA' has been changed only on Angular 1.3.

**Comment by jeffcarp** [comment]
Cool, thanks for digging. Do you want to update the PR / make a new one with just the `restrict: 'AEC'`?

**Comment by gambry** [comment]
yep, made a new one.
