### ISSUE TITLE
Destroying Braintree items on destroying the form

### ISSUE THREAD

**Issue by gambry** [jeffcarp/braintree-angular#19]
On submitting the form with any method, the Braintree items are automatically destroyed.

But if a custom `onPaymentMethodReceived` callback is defined, on `$destroy`ing the directive, all the relative items have to be deleted.

So far I worked only with dropIn and I found left in the DOM only the braintree iframe and the window.Braintree object, but probably there is more stuff somewhere else and/or using the other directive.

**Comment by jeffcarp** [comment]
> probably there is more stuff somewhere else

Unfortunately there is: https://github.com/braintree/braintree-web/issues/29

I'm not sure how I feel about removing some of Drop-In but not all of it on `$destroy` :confused:

**Comment by gambry** [comment]
Cool, I've searched an existing issue on braintree-web without success. So thank you for the link.

I agree the destroy() should come from braintree and not done by other modules.

I'll then do it locally on my controller until the solution will come by itself from braintree.

**Comment by jeffcarp** [comment]
Sounds good :+1: thanks for bringing this up :)
