### ISSUE TITLE
Warning from Webpack build process

### ISSUE THREAD

**Issue by kpgarrod** [jeffcarp/braintree-angular#29]
I am using braintree-angular in a Typescript project which is build using webpack. I include the package in my project with `require('braintree-angular')`. The build process gives me the following warning:
     
    WARNING in ./~/braintree-angular/~/braintree-web/dist/braintree.js
    Critical dependencies:
    2:443-450 This seems to be a pre-built javascript file. 
    Though this is possible, it's not recommended. 
    Try to require the original source to get better results.
     @ ./~/braintree-angular/~/braintree-web/dist/braintree.js 2:443-450

Although I haven't got as far as actually making a call to Braintree, it seems that  the library is included correctly and the message is nothing worse than an irritation, but I thought I would let you know anyway.

**Comment by jeffcarp** [comment]
Thanks for bringing this up, @kpgarrod. `braintree-angular` itself is not minified, but its main dependency, `braintree-web`, is only available in minified form - thus I don't think there's a way to prevent that warning at the moment.
