### ISSUE TITLE
How to use braintree-angular with ui-router

### ISSUE THREAD

**Issue by opiedog** [jeffcarp/braintree-angular#35]
My Angular app uses the angular-ui/ui-router library. I think it's conflicting with this initial call to configure braintree-angular:
```
.constant("clientTokenPath", "/paymentGateways/get_client_token")
```

The call to the get_client_token function returns my app's default route (i.e. my index.html). This is the same behavior if I try calling a nonexistent state like this:
```
$state.go("non-existent-route")
```

Does braintree-angular work with ui-router? If so, am I using the wrong syntax for the clientTokenPath value? Should it be a state name (I tried that but it didn't work)? Something else?

Thanks!

**Comment by monali01** [comment]
I have an angular app with ui-router and I was able to get it working successfully.
It seems like you are using angular route for "clientTokenPath" constant instead of using your server API endpoint. "ClientTokenPath" requires back-end api endpoint which would return braintree client token.

You should look into Braintree server-side documentation for this. Braintree -angular library is only front-end code.

**Comment by opiedog** [comment]
Hmm... I do indeed have this endpoint in my server:
```python
/paymentGateways/get_client_token
```

I started down the path of rolling my own client code when I saw the braintree-angular library. That endpoint definitely works which is why I figured there must be something going on with ui-router.

Well thanks for confirming that it does work with ui-router. I'll have to keep clicking around to see how to make this work.

Actually, is there a way to manually set the client token in the braintree-angular instance instead of having it get the value from my server API?

**Comment by monali01** [comment]
You can set it manually in Braintree-angular.js file but you will have to make few changes since it is written to make $http call to get the client token. So it would be hard to just copy-paste token in the library.

If you post your code here, I can try to help with it.

**Comment by monali01** [comment]
Also, is your API and client running under same application server? If not, you will have to provide full path to back-end API for clientTokenPath.

For example: 
`.constant("clientTokenPath", "http://localhost:9000/paymentGateways/get_client_token")`

**Comment by jeffcarp** [comment]
> is there a way to manually set the client token in the braintree-angular instance instead of having it get the value from my server API?

Client tokens should be fetched fresh from the server (where they're generated by a Braintree server library).

Thanks for the help so far @monali01

**Comment by opiedog** [comment]
Part of the problem was the need for the full path to the API. The braintree-angular lib is now hitting the right endpoint but it generates an HTTP 301. I verified that it's hitting the right endpoint by copy-pasting the value from the browser network inspector and confirming it works in postman, from the Django REST framework API page (whatever it's called), and from a test button in the app. But when braintree-angular calls that same URL it gets a 301 redirect.

Any ideas?

Thanks for your help so far. I appreciate it!

**Comment by opiedog** [comment]
One more bit of data:
I modified the braintree-angular sample like this:
```
      var port = 8001;      // don't conflict with my app's port
      . . .
      angular.module('example', ['braintree-angular'])
             //.constant('clientTokenPath', '/client-token');
             .constant('clientTokenPath', 'http://localhost:8000/paymentGateways/get_client_token');
```
And it worked. So my app's API definitely does not seem to be the problem.

And since there are no issues with any other REST APIs in my app, it seems the problem might be related to the configuration of the braintree-angular library, or maybe there was a failure when I installed it that I didn't notice, or I'm not including it properly in my app?

What I did to add it to my app was the following:
```
npm install braintree-angular
bower install braintree-angular

<script src="/lib/braintree-angular.js"></script>

angular.module("cagering", ["ui.router", ... ,"braintree-angular"])
```

And to be clear, the sample app works fine so I don't think npm/bower installs ran into any problems...

**Comment by monali01** [comment]
What is `var port = 8001;` for?
if that is your server port, your clientTokenPath needs use 8001 instead of 8000.

Your rest of the configuration looks right. 301 could have many reasons. Your api might require authorized call. 

How are you populating braintree button, do you mind posting your html and JavaScript part of that?

**Comment by jeffcarp** [comment]
Hey @opiedog I'm sorry this is ambiguous in the README but you should only need to install with `npm` or `bower`. Since you're including the module with a script tag, it looks like you only need to install with `bower`.

**Comment by opiedog** [comment]
The 8001 thing was to avoid port collision while I was testing. But I just found the issue although I still don't understand it.

When I did this in the *sample app* it worked:
```
.constant('clientTokenPath', 'http://localhost:8000/paymentGateways/get_client_token')
```

But it didn't work in my app. Then I got the crazy idea to just toss a slash on the path like this and it worked in *my app*:
```
.constant("clientTokenPath", "http://localhost:8000/paymentGateways/get_client_token/")
```

I have no idea why that's the case, but for whatever reason it's working now and I'm unblocked. If you have an idea what might be going on there I'd love to hear it. Otherwise, I will happily trudge forward blissfully ignorant of that detail and see if I can get this whole thing to work.

Thanks for your help and for creating what looks like a really nice library to ease the integration with Braintree!

**Comment by azeredudu1** [comment]
I'm stuck , can someone help me, i'm having this error : error fetching client token at /api/braintree/client_token <!DOCTYPE html>

**Comment by jeffcarp** [comment]
hi @azeredudu1 what does your `clientTokenPath` setup look like?

**Comment by azeredudu1** [comment]
I'm using angular and node ,
Controller : .constant('clientTokenPath', '/api/braintree/client_token')
In routes.js: 
 app.use('/api/braintrees', require('./api/braintree'));

In braintree.model.js
var braintree = require('braintree');
var config = require('../../config/environment');
var isProduction = config.env === 'production';

var gateway = braintree.connect({
  environment: isProduction ? braintree.Environment.Production : braintree.Environment.Sandbox,
  merchantId: config.braintree.clientMerchant,
  publicKey: config.braintree.clientID,
  privateKey: config.braintree.clientSecret
});

module.exports = gateway;

in local.env.js:
BRAINTREE_ID : 'shxg------------',
	BRAINTREE_SECRET : '2d.....................',
	BRAINTREE_MERCHANT : 'wj...........................4',


in braintree.controller.js : 
exports.clientToken = function(req, res){
  Braintree.clientToken.generate({}, function (err, data) {
    return handleResponse(res)(err, data.clientToken);
  });
}
Thanks .

**Comment by jeffcarp** [comment]
From the above error it looks like your client token route is outputting HTML instead of JSON.

**Comment by azeredudu1** [comment]
so how do i solve the matter?

**Comment by jeffcarp** [comment]
Sorry I don't have the bandwidth to help you debug here - you can try reaching out to support@braintreepayments.com for integration issues
