### ISSUE TITLE
cordova integration

### ISSUE THREAD

**Issue by denkomanceski** [jeffcarp/braintree-angular#38]
Hi, I have a small problem: using the braintree js in ionic 2 app (using angular 2) the paypal button does not work. After some research I found about this braintree angular library. Is there any way how to use it with Angular 2 ? THanks

**Comment by jeffcarp** [comment]
Hi @denkomanceski, this module doesn't currently support Angular 2. I don't have a ton of context on Angular 2 but I'd love to figure out if we could get it working.
