### ISSUE TITLE
Support for custom

### ISSUE THREAD

**Issue by JoomSavvy** [jeffcarp/braintree-angular#39]
Trying to adapt this for using the custom directive on the braintree sdk. Of course the directive isn't processing the dom before it runs the braintree.setup. Have you made any progress in this direction?

**Comment by jeffcarp** [comment]
Hi @JoomSavvy, thanks for looking into this. Are you talking about the basic custom integration or Hosted Fields? I experimented with it about a year ago but didn't get too far.

**Comment by JoomSavvy** [comment]
Hosted Fields. If you check out my fork, you can see I've added a directive. I'm creating the field holders in the directive and if you debug in chome and step through execution they are there in the dom when $bt.setup(token,'custom,{}) executes, but it skips the custom function and starts look for [data-braintree=name] for the two required fields, number and exp date.

**Comment by jeffcarp** [comment]
Hey @JoomSavvy I'm having a hard time finding your code, is this the right place to look? https://github.com/jeffcarp/braintree-angular/compare/master...JoomSavvy:custom

**Comment by JoomSavvy** [comment]
sorry, gave up
