### ISSUE TITLE
Unknown provider: clientTokenPathProvider

### ISSUE THREAD

**Issue by JDqv** [jeffcarp/braintree-angular#4]
Im running into strange issue when I try to wrap braintree-angular with ui router.
Basically, when I do
```
angular.module('example', ['braintree-angular'])
  .constant('clientTokenURL', '/braintree-token')
  .config(['$stateProvider', '$urlRouterProvider',
    function ($stateProvider, $urlRouterProvider) {
      $stateProvider.state('public.pay', {
        url: '/pay',
        templateUrl: 'pay'
      });
  }]);
```
template uses directive, simplest version

```
h1 This is Braintree payment page
  form(action='/buy-something', method='post')
    h1 Buy some things
    braintree-dropin Loading payment form...
    input(type='submit', value='Buy for $10')
```

Template loads and console spits out Unknown provider: clientTokenPathProvider error.

This might be related to my limited experience with angular, rather than braintree-angular itself, I realize that.

**Comment by Kratos-SA** [comment]
Hi I am using the new version and still getting this bug

**Comment by jeffcarp** [comment]
@Kratos-SA sorry for the late reply - what version are you using?

**Comment by Kratos-SA** [comment]
We where able to resolve this. But then we realized that its not supported
in our country. FML/

On 12 June 2016 at 02:08, Jeff Carpenter <notifications@github.com> wrote:

> @Kratos-SA <https://github.com/Kratos-SA> sorry for the late reply - what
> version are you using?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jeffcarp/braintree-angular/issues/4#issuecomment-225401514>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADMeUKtPgFRYZrt82QqBCztBeAyXweHSks5qK031gaJpZM4DIhod>
> .
>



-- 
Ross Rawlins
*Tel:* 021 531 7087
*Cell:* 072 424 9480
*Skype:* ross.rawlins
*Email:* ross@duovili.co.za

<http://www.duovili.co.za>
<https://plus.google.com/113781084234234096576/posts>
<https://www.facebook.com/Duovili>
<http://www.linkedin.com/company/duovili/>     <https://twitter.com/Duovili>


This e-mail message and all attachments contain the CONFIDENTIAL AND
PROPRIETARY information of DUOVILI DEVELOPMENTS. and may contain LEGALLY
PRIVILEGED information. If you are not the intended recipient, you are
hereby notified that any disclosure, distribution, or use of this e-mail,
its attachments or any information contained therein is unauthorised and
prohibited. If you have received this in error, please contact the sender
immediately and delete this e-mail and any attachments.
