### ISSUE TITLE
Clarification on structure

### ISSUE THREAD

**Issue by ghego1** [jeffcarp/braintree-angular#40]
Hello, just found this module, which sounds awesome, but I have a doubt: does it expose all web-braintree functions? Or is it limited somehow to only certain features?
Thanks!

**Comment by jeffcarp** [comment]
The directives are limited in functionality. 

The module does expose a $braintree service you can inject which you can use if you want to do things manually e.g. $braintree.setup(...)

I hope to improve the comprehensiveness of this module. Any help would be appreciated!

**Comment by ghego1** [comment]
Ok thanks! I'm new to braintree, but if I can help I will! :-)
