### ISSUE TITLE
Paypal braintree drop-in mobile.

### ISSUE THREAD

**Issue by fhackenb** [jeffcarp/braintree-angular#41]
Hello, I'm using braintree-angular for my Ionic (angular-based) mobile app. I copied the dropin code from your demo which displays the paypal button. When I click it however, the popup form to checkout.paypal.com does not appear. Instead I just see the overlay saying "Don't see secure PayPal browser?...". I have the same code working on the web browser, so I was wondering if there's a trick to getting it to work on mobile. I've tried modifying the source code in braintree-angular.js but to no success. 

Thanks

**Comment by fhackenb** [comment]
Here's my html: 
<braintree-paypal
        options="vm.paypalOptions"
        >Loading PayPal button...</braintree-paypal>
And my js:

self.paypalOptions = {
       onPaymentMethodReceived: function(payload) {
         console.log('Yay, payload with nonce:', payload);
         self.paypalNonce = payload.nonce;
       }
     };

**Comment by jeffcarp** [comment]
Hi @fhackenb, sorry for the late reply. I don't think Ionic is an officially supported integration. I'm not sure what it would take to get it running.
