### ISSUE TITLE
Typo on Setup Section

### ISSUE THREAD

**Issue by bytenel** [jeffcarp/braintree-angular#5]
Hey guys!

I noticed you don't declare the dependency for 'braintree-angular' in the README here but you do so in the examples in the directory. Probably should rectify this!

**Comment by jeffcarp** [comment]
Hey @bytenel, did you mean like these?

```html
<script src="/angular.js"></script>
<script src="/braintree-angular.js"></script>
```

I left them out for brevity and because people might have their own build processes that combine the two files.

**Comment by bytenel** [comment]
Yup your edit has it spot on! Def added a little confusion haha! Yay helping the open source community! My neckbeard grows +1

**Comment by jeffcarp** [comment]
Thanks! :beers:
