### ISSUE TITLE
Braintree Angular with Bower Issue?

### ISSUE THREAD

**Issue by bytenel** [jeffcarp/braintree-angular#6]
<code>
_prelude.js:1 Uncaught Error: Cannot find module './braintree-factory'_prelude.js:1 s_prelude.js:1 (anonymous function)braintree-angular.js:50 2../braintree-factorybraintree-angular.js:5 sbraintree-angular.js:5 ebraintree-angular.js:5 browserifyShimbraintree-angular.js:99 (anonymous function)braintree-angular.js:101 /Users/bytenel/workspace/exposure_tracker/bower_components/braintree-angular/dist/braintree-angular.js./Users/bytenel/workspace/exposure_tracker/bower_components/angular/angular.min.js_prelude.js:1 s_prelude.js:1 (anonymous function)main.js:45 (anonymous function)main.js:85 ./client/scripts/main.js../controllers/modalCtrl_prelude.js:1 s_prelude.js:1 e_prelude.js:1 (anonymous function)
angular.min.js:8 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.8/$injector/modulerr?p0=main&p1=Error%3A%20…%20at%20d%20(http%3A%2F%2F0.0.0.0%3A5000%2Fscripts%2Fbundle.js%3A159%3A350)angular.min.js:8 (anonymous function)angular.min.js:38 (anonymous function)angular.min.js:9 sangular.min.js:37 gangular.min.js:40 Obangular.min.js:19 dangular.min.js:20 scangular.min.js:18 Jdangular.min.js:251 (anonymous function)jquery.min.js:4 jjquery.min.js:4 k.fireWithjquery.min.js:4 n.extend.readyjquery.min.js:4 I
</code>

So when I install from bower and use browserify to include the module I get this error...am I configuring something wrong?

**Comment by jeffcarp** [comment]
Interesting, I'm not sure what's going wrong from that trace but can you try pointing browserify at this file instead? https://github.com/jeffcarp/braintree-angular/blob/master/dist/braintree-angular.js

**Comment by bytenel** [comment]
I'm not entirely sure how to do that honestly...in my package.json where I'm defining what braintree-angular is when I put that as the URL it tells me it cant find it in my repo (which makes sense) I'm not sure how to point it externally. 

BTW I tried the same thing with the NPM package and got the same result.

**Comment by bytenel** [comment]
If I change line 47 of braintree-angular.js to 
<code>
var braintreeFactory = braintreeFactory;
</code>

The browserify works but I don't think that's what you were intending.

**Comment by jeffcarp** [comment]
I haven't tried building this module with browserify so it may very well just not be set up correctly. Can you try including it like this (assuming you already have it installed via npm)?

```js
require('braintree-angular/dist/braintree-angular.js');
```

**Comment by bytenel** [comment]
Project I was working on that used it was shut down, but thank you so much for the assistance! If I use the project in the future I'll be sure to let you know if I run into issues.

**Comment by jeffcarp** [comment]
No worries, happy coding :smile:

**Comment by KoalaOnAStick** [comment]
Hi @jeffcarp,

I seem to have the same issue as @bytenel .

I've tried requiring the braintree-angular.js file directly as you proposed but no success --> I still get the same issue as bytenel indicated.

I don't mind shimming braintree-angular to get it to work, but even there I'm stumped ;)

Any idea how to fix this?

**Comment by jeffcarp** [comment]
Hey @KoalaOnAStick, can you give me more information on your build pipeline? Are you using Browserify? Can you give steps to reproduce?

**Comment by KoalaOnAStick** [comment]
Hi @jeffcarp,

Sure, thanks for the quick reply. Yes, I'm using Browserify to build.

Here's how to recreate the issue:

**cmd**
`npm install braintree-angular` 

**app.js**
```
var app = angular.module('app',[
    require('angular-resource'),
    require('angular-animate'),
    require('angular-sanitize'),
    require('angular-cookies'),
    require('angular-ui-router'),
    // More requires here
    require('braintree-angular')
]).constant('clientTokenPath', '/api/clienttoken');
```
**cmd**
`browserify app.js -o bundle.js`


I've had to shim some other components we're using, but I can't manage to figure out how to do this with this component. Given that I got the impression that you wanted this component to be CommonJS, I thought it would be best to ask you directly ;) If shimming is the way to go, I can also show you what I tried.

**Comment by jeffcarp** [comment]
Unfortunately running those steps on my machine ran fine - I didn't get an error like in the first post in this thread. Are you getting an error when you run `browserify` or when you try to run the JS? Could it be a version issue with some dependency? Here are the versions I was using to reproduce:

- `angular-resource@1.4.5`
- `angular@1.4.5`
- `braintree-angular@1.3.1`
- `browserify@11.0.1`
- NodeJS at `iojs-3.1.0`
- on Debian Jessie

**Comment by KoalaOnAStick** [comment]
Hey @jeffcarp,

Indeed, when trying it with a minimal setup it does seem to work - going to investigate it further and see which component causes the trouble. Will keep you up to date - feel free to close the issue in between.
