### ISSUE TITLE
Allow CVV to be inputted in non-dropin UI

### ISSUE THREAD

**Issue by KoalaOnAStick** [jeffcarp/braintree-angular#7]
Hi,

The current code doesn't seem to allow a CVV to be inputted in a <b>non-dropin UI</b> setting.

Would it be possible to implement this?

Thanks in advance!

Also - great module!

**Comment by jeffcarp** [comment]
Hi @KoalaOnAStick, by non-dropin UI do you mean custom (attaching at a form) or advanced (tokenizeCard)? What do you mean by can't be inputted?

**Comment by KoalaOnAStick** [comment]
Hi Jeff,

Woops, sorry, after re-reading I realize my question wasn't very clear.

Here's the issue:
Example HTML:

    <div ng-app="yourApp" ng-controller="yourCtrl">
        <input ng-model="creditCard.number" placeholder="4111111111111111" />
        <input ng-model="creditCard.expirationDate" placeholder="10/18" />
        <input ng-model="creditCard.CVV" placeholder="100" />
        <button ng-click="payButtonClicked()"/>Pay!</button>
    </div>

Example JS:

    angular.module('yourApp', ['braintree-angular'])
        .constant('clientTokenPath', '/client-token')
        .controller('yourCtrl', ['$scope', '$braintree', function($scope, $braintree) {

    var client;
    $scope.creditCard = {
        number: '',
        expirationDate: '',
        CVV:''
    };

    var startup = function() {
        $braintree.getClientToken().success(function(token) {
            client = new $braintree.api.Client({
                clientToken: token
            });
        });
    }

    $scope.payButtonClicked = function() {
      // - Validate $scope.creditCard
      // - Make sure client is ready to use

    client.tokenizeCard({
        number: $scope.creditCard.number,
        expirationDate: $scope.creditCard.expirationDate
        CVV:$scope.creditCard.CVV //- This field seems to be the issue
    }, function (err, nonce) {
        // - Send nonce to your server (e.g. to make a transaction)
        });
    };
    startup();
    }]);

The tokenizeCard only seems to accept number, expirationDate, expirationYear and expirationMonth. I would like to add CVV (and ideally also cardholder name). Unless I'm mistaken, this doesn't seem to work.

Could you verify?

Thanks in advance!

**Comment by KoalaOnAStick** [comment]
@jeffcarp,

Hi Jeff, I figured out my issue: I stupidly wrote  "CVV" instead of "cvv". Everything works perfectly - my apologies for the stupid mistake!

Perhaps it would be useful in the example to add the full set of options for tokenizeCards? Would gladly do this if you're ok with it jeff.

**Comment by jeffcarp** [comment]
:fire: :imp: javascript!! :fire: 

Glad you figured it out! The full set of options are [available here](https://developers.braintreepayments.com/javascript/sdk/client/credit-cards#options). I will update the README.

Also please be advised (I should also add this to the README) that using the advanced integration widens your PCI compliance scope (to SAQ-C if I understand it correctly).
