### ISSUE TITLE
paypal support?

### ISSUE THREAD

**Issue by keshavkaul** [jeffcarp/braintree-angular#8]
Is paypal supported?

Using normal braintree-web script from url https://js.braintreegateway.com/v2/braintree.js, i am facing a issue where onSuccess Callback gets called twice when using braintree.setup with paypal type.

**Comment by jeffcarp** [comment]
Sorry this isn't better documented, with braintree-angular you don't need to call `braintree.setup`. Just add your PayPal options to `$scope.dropinOptions` and you should be set: https://github.com/jeffcarp/braintree-angular/blob/master/examples/dropin/nonce-received.html#L31

**Comment by keshavkaul** [comment]
Sorry if i wasn't clear, but i am looking for a PayPal only integration, which is possible using `braintree.setup`. 

But using it with angular, i am experiencing the issue of `onSuccess` callback getting called twice when authorizing PayPal account. (this i think is because `braintree.setup` is getting called more than once whenever the angular controller gets initialized on route change.)

Would really appreciate your thoughts on how Braintree PayPal integration would work with a SPA like angular.

**Comment by jeffcarp** [comment]
Ah, understood. Unfortunately braintree-web is not currently set up to work well in SPA contexts (see issues like https://github.com/braintree/braintree-web/issues/18).

Would it fix your problem if you made sure `braintree.setup` was only called once?

**Comment by keshavkaul** [comment]
From the way i understand it, i need to call braintree.setup in order to show the paypal button. 
I have to collect payment from 3 pages. So in each page i call `braintree.setup` once. But on changing the routes to other payment collection pages, effectively `braintree.setup` is called more than once. Don't know how i can avoid that.

Your solution provided in https://github.com/braintree/braintree-web/issues/18 wasn't successful in solving this problem.

Thanks.

**Comment by jeffcarp** [comment]
Hey @keshavkaul, unfortunately `braintree.setup` isn't currently designed to be called more than once. Is there a way to keep the DOM node that it was called on around somewhere and surface that on different pages?
